-- ZX Spectrum Screenshot Capture (Manual)
-- This script provides instructions for manual screenshot capture
-- since automated TAP file creation requires additional tools

print("ZX Spectrum Screenshot Capture")
print("================================")
print("")
print("To capture a screenshot of hello-spectrum.bas:")
print("")
print("1. Launch Fuse emulator: fuse")
print("2. Type in the BASIC program:")
print("   10 REM Hello, Spectrum World")
print("   20 REM Display text with color")
print("   30 BORDER 5")
print("   40 PAPER 5")
print("   50 INK 7")
print("   60 CLS")
print("   70 PRINT AT 10,8;\"HELLO, SPECTRUM!\"")
print("   80 PAUSE 0")
print("")
print("3. Run the program: RUN")
print("4. Capture screenshot: Media -> Save Screenshot")
print("5. Save as PNG in: website/public/images/zx-spectrum/phase-1/tier-1/lesson-001/")
print("")
print("Alternative: Use Fuse's --screenshot option")
print("")
